Repository Couchers-org/couchers, pull requests merged in 2024-12, with the labels that each got.

#5306 Mobile style fixes for references list
  app/web/components/TabBar/TabBar.tsx
  app/web/features/profile/view/ReferenceList.tsx
  app/web/features/profile/view/ReferenceListItem.tsx
Labels: 1.topic frontend, mobile

#5302 Web/feature/report a bug (issue #5274)
  app/web/components/Navigation/LoggedInMenu.tsx
  app/web/components/Navigation/ReportButton.stories.tsx
Labels: 1.topic frontend

#5301 Web/bugfix/spinner placement (issue #5026)
  app/web/components/AppRoute.tsx
  app/web/components/CenteredSpinner/CenteredSpinner.stories.tsx
  app/web/components/CenteredSpinner/CenteredSpinner.tsx
  app/web/components/Comments/CommentBox.tsx
  app/web/components/ContributorForm/StandaloneContributorForm.tsx
  app/web/components/FullPageLoader/FullPageLoader.stories.tsx
  app/web/components/FullPageLoader/FullPageLoader.tsx
  app/web/components/FullPageLoader/index.ts
  app/web/components/TOS.tsx
  app/web/features/auth/CommunityGuidelines.tsx
  app/web/features/auth/FeaturePreview.tsx
  app/web/features/auth/Logout.tsx
  app/web/features/auth/Settings.tsx
  app/web/features/auth/email/DoNotEmail.tsx
  app/web/features/auth/jail/Jail.tsx
  app/web/features/auth/logins/LoginsPage.tsx
  app/web/features/auth/signup/Signup.tsx
  app/web/features/communities/CommunityBase.tsx
  app/web/features/communities/CommunityModeratorsDialog.tsx
  app/web/features/communities/CommunityModeratorsSection.tsx
  app/web/features/communities/CommunityPage/PlacesSection.tsx
  app/web/features/communities/GroupPage.tsx
  app/web/features/communities/NewGuideForm.tsx
  app/web/features/communities/NewPlaceForm.tsx
  app/web/features/communities/PagePage.tsx
  app/web/features/communities/discussions/Comment.tsx
  app/web/features/communities/discussions/CommentTree.tsx
  app/web/features/communities/discussions/DiscussionPage.tsx
  app/web/features/communities/discussions/DiscussionsListPage.tsx
  app/web/features/communities/discussions/DiscussionsSection.tsx
  app/web/features/communities/events/CommunityEventsList.tsx
  app/web/features/communities/events/DiscoverEventsList.tsx
  app/web/features/communities/events/EditEventPage.tsx
  app/web/features/communities/events/EventAttendeesDialog.tsx
  app/web/features/communities/events/EventOrganizersDialog.tsx
  app/web/features/communities/events/EventPage.tsx
  app/web/features/communities/events/EventUsers.tsx
  app/web/features/communities/events/EventsSection.tsx
  app/web/features/communities/events/EventsTab.tsx
  app/web/features/communities/events/MyEventsList.tsx
  app/web/features/connections/friends/FriendRequestsReceived.tsx
  app/web/features/connections/friends/FriendRequestsSent.tsx
  app/web/features/dashboard/CommunityBrowser.tsx
  app/web/features/dashboard/DashboardUserProfileSummary.tsx
  app/web/features/dashboard/MyEvents.tsx
  app/web/features/messages/groupchats/AdminsDialog.tsx
  app/web/features/messages/groupchats/ChatContent.tsx
  app/web/features/messages/groupchats/GroupChatsTab.tsx
  app/web/features/messages/groupchats/MembersDialog.tsx
  app/web/features/messages/requests/RequestsTab.tsx
  app/web/features/profile/edit/EditHostingPreference.tsx
  app/web/features/profile/edit/EditProfile.tsx
  app/web/features/profile/view/ProfilePage.tsx
  app/web/features/profile/view/ReferencesView.tsx
  app/web/features/profile/view/UserPage.tsx
  app/web/features/profile/view/leaveReference/LeaveReferencePage.tsx
  app/web/features/search/MapWrapper.tsx
  app/web/features/search/SearchResultsList.tsx
Labels: 1.topic frontend

#5298 Fix: Improve Label Alignment and Spacing in Profile View (Issue #4973)
  app/web/components/LabelAndText.tsx
  app/web/features/profile/view/userLabels.tsx
Labels: 1.topic frontend

#5332 Update backend to use new redirect system for SV
  app/backend/src/couchers/servicers/account.py
  app/backend/src/couchers/urls.py
  app/backend/src/tests/test_strong_verification.py
  app/proto/account.proto
Labels: 1.topic backend

#5336 Make dialogs prettier
  app/web/components/Dialog.tsx
Labels: 1.topic frontend

#5331 Update email change confirmation template, closes #5327
  app/backend/templates/v2/email_changed_confirmation_new_email.mjml
  app/backend/templates/v2/generated_html/email_changed_confirmation_new_email.html
Labels: 1.topic backend

#5333 Add frontend SV
  app/web/features/auth/locales/en.json
  app/web/features/auth/verification/CompleteStrongVerification.tsx
  app/web/features/auth/verification/DeleteStrongVerificationDataButton.tsx
  app/web/features/auth/verification/StartStrongVerificationButton.tsx
  app/web/features/auth/verification/StrongVerification.tsx
  app/web/pages/complete-strong-verification.tsx
  app/web/service/account.ts
Labels: 1.topic frontend, release notes: pending
