Repository Couchers-org/couchers, pull requests merged in 2024-11, with the labels that each got.

#5052 Map pin coloring based on completed profile
  app/web/features/search/users.ts
Labels: release notes: pending

#4951 Switch to getLiteUser where applicable on frontend
  app/web/components/Avatar/Avatar.tsx
  app/web/components/UserSummary.tsx
  app/web/features/communities/discussions/Comment.tsx
  app/web/features/communities/discussions/DiscussionCard.tsx
  app/web/features/communities/discussions/DiscussionPage.test.tsx
  app/web/features/communities/discussions/DiscussionPage.tsx
  app/web/features/communities/discussions/DiscussionsListPage.test.tsx
  app/web/features/communities/events/EventUsers.tsx
  app/web/features/connections/friends/FriendSummaryView.tsx
  app/web/features/connections/friends/useFriendRequests.test.tsx
  app/web/features/connections/friends/useFriendRequests.ts
  app/web/features/messages/groupchats/AdminsDialog.tsx
  app/web/features/messages/groupchats/GroupChatListItem.tsx
  app/web/features/messages/groupchats/GroupChatView.test.tsx
  app/web/features/messages/groupchats/GroupChatView.tsx
  app/web/features/messages/groupchats/MembersDialog.tsx
  app/web/features/messages/messagelist/ControlMessageView.tsx
  app/web/features/messages/messagelist/MessageView.tsx
  app/web/features/messages/requests/HostRequestListItem.tsx
  app/web/features/messages/requests/HostRequestView.tsx
  app/web/features/messages/utils.ts
  app/web/features/profile/view/NewHostRequest.tsx
  app/web/features/profile/view/ReferenceList.tsx
  app/web/features/profile/view/ReferenceListItem.tsx
  app/web/features/profile/view/References.test.tsx
  app/web/features/profile/view/ReferencesGivenList.tsx
  app/web/features/profile/view/ReferencesReceivedList.tsx
  app/web/features/profile/view/ReferencesView.tsx
  app/web/features/profile/view/leaveReference/formSteps/submit/SubmitReference.tsx
  app/web/features/queryKeys.ts
  app/web/features/userQueries/useLiteUsers.test.tsx
  app/web/features/userQueries/useLiteUsers.ts
  app/web/service/conversations.ts
  app/web/service/user.ts
  app/web/test/fixtures/liteUsers.json
  app/web/test/serviceMockDefaults.ts
Labels: 1.topic frontend, release notes: pending

#5105 Step 1: Upgrade maplibre to version 2.4.0
  app/web/.env.development
  app/web/.env.localdev
  app/web/.env.next
  app/web/.env.production
  app/web/components/EditLocationMap.test.tsx
  app/web/components/EditLocationMap.tsx
  app/web/components/Map.tsx
  app/web/features/search/MapWrapper.tsx
  app/web/features/search/communities.ts
  app/web/features/search/constants.ts
  app/web/features/search/guides.ts
  app/web/features/search/places.ts
  app/web/features/search/users.ts
  app/web/package.json
  app/web/yarn.lock
  docs/web-frontend.md
Labels: 1.topic frontend

#5083 Create ui-ux-designer.md volunteer recruitment page
  app/web/markdown/volunteer/ui-ux-designer.md
Labels: site

#4769 Add links to guides in various places
  app/web/components/ProfileIncompleteDialog/ProfileIncompleteDialog.tsx
  app/web/features/auth/phone/ChangePhone.tsx
  app/web/features/communities/events/InviteCommunityDialog.tsx
  app/web/features/messages/locales/en.json
  app/web/features/messages/requests/HostRequestSendField.tsx
  app/web/features/messages/useSendFieldStyles.ts
  app/web/features/profile/edit/EditProfile.tsx
  app/web/features/profile/edit/styles.ts
  app/web/features/profile/locales/en.json
  app/web/features/profile/view/NewHostRequest.tsx
  app/web/routes.ts
Labels: release notes: pending

#5214 update language heading on edit profile
  app/web/features/profile/locales/en.json
Labels: 1.topic frontend

#5258 Hide response buttons for past requests
  app/web/features/messages/requests/HostRequestGuideLinks.tsx
  app/web/features/messages/requests/HostRequestRespondButtons.tsx
  app/web/features/messages/requests/HostRequestSendField.tsx
  app/web/routes.ts
Labels: release notes: pending

#5268 Add Listmonk to open-source.md
  app/web/markdown/open-source.md
Labels: site, 1.topic frontend, improvement
