Repository Couchers-org/couchers, pull requests merged in 2025-02, with the labels that each got.

#5261 Users by badge
  .gitignore
  app/web/features/badges/Badge.tsx
  app/web/features/badges/BadgeUserList.tsx
  app/web/features/badges/BadgesPage.tsx
  app/web/features/badges/hooks.ts
  app/web/features/communities/events/EventUsers.tsx
  app/web/features/profile/hooks/useBadges.ts
  app/web/features/profile/locales/en.json
  app/web/features/profile/view/Badges.tsx
  app/web/features/queryKeys.ts
  app/web/pages/badges/[id].tsx
  app/web/pages/badges/index.tsx
  app/web/resources/locales/en.json
  app/web/routes.ts
  app/web/service/api.ts
Labels: 1.topic frontend, release notes: pending

#5621 Correct country code for PSE
  app/web/public/regions.json
Labels: 1.topic frontend

#5637 Update Other pages “roadmap”
  app/web/markdown/roadmap.md
Labels: cms/pending_review
