Repository Couchers-org/couchers, pull requests merged in 2025-01, with the labels that each got.

#5413 frontend - add clear filter button #5275
  app/web/features/auth/notifications/useNotificationSettings.test.ts
  app/web/features/search/FilterDialog.tsx
  app/web/features/search/MapWrapper.tsx
  app/web/features/search/SearchPage.test.tsx
  app/web/features/search/SearchPage.tsx
  app/web/features/search/locales/en.json
Labels: 1.topic frontend

#5260 Allow messaging past reqs
  app/backend/src/couchers/servicers/requests.py
  app/web/features/messages/locales/en.json
  app/web/features/messages/requests/HostRequestGuideLinks.tsx
  app/web/features/messages/requests/HostRequestSendField.tsx
Labels: release notes: pending

#5505 Didn't meet up backend
  app/backend/src/couchers/errors.py
  app/backend/src/couchers/jobs/handlers.py
  app/backend/src/couchers/migrations/versions/99aece5bdc42_add_didnt_meetup_feature.py
  app/backend/src/couchers/models.py
  app/backend/src/couchers/servicers/references.py
  app/backend/src/tests/test_bg_jobs.py
  app/backend/src/tests/test_references.py
  app/proto/references.proto
Labels: release notes: pending

#5556 Update open-source.md
  app/web/markdown/open-source.md
Labels: site
