Repository Couchers-org/couchers, pull requests merged in 2025-05, with the labels that each got.

#5945 Update Other pages “roadmap”
  app/web/markdown/roadmap.md
Labels: cms/pending_publish

#5966 Update Other pages “roadmap”
  app/web/markdown/roadmap.md
Labels: cms/pending_publish

#5980 Create Blog “2025/05/09/how-to-add-couchers-org-or-any-website-to-your-phone’s-home-screen-for-instant-access”
  app/web/markdown/blog.md
  app/web/markdown/blog/2022/03/13/hosting-refugees-and-finding-shelter-with-couchers-org-en.md
  app/web/markdown/blog/2022/03/13/hosting-refugees-and-finding-shelter-with-couchers-org-hu.md
  app/web/markdown/blog/2022/03/13/hosting-refugees-and-finding-shelter-with-couchers-org-pl.md
  app/web/markdown/blog/2022/03/13/hosting-refugees-and-finding-shelter-with-couchers-org-ro.md
  app/web/markdown/blog/2022/03/13/hosting-refugees-and-finding-shelter-with-couchers-org-uk.md
  app/web/markdown/blog/2025/05/10/how-to-add-couchers-org-phone-home-screen.md
Labels: cms/pending_publish

#6030 Add API to remove friends
  app/backend/src/couchers/errors.py
  app/backend/src/couchers/servicers/api.py
  app/backend/src/tests/test_api.py
  app/proto/api.proto
Labels: release notes: pending

#6042 Update volunteer.md
  app/web/markdown/volunteer.md
Labels: 1.topic frontend

#6038 Implement blog post notifs
  app/backend/proto/internal/jobs.proto
  app/backend/src/couchers/errors.py
  app/backend/src/couchers/jobs/handlers.py
  app/backend/src/couchers/migrations/versions/07ecff50fe93_add_blog_post_notifs.py
  app/backend/src/couchers/models.py
  app/backend/src/couchers/notifications/render.py
  app/backend/src/couchers/notifications/settings.py
  app/backend/src/couchers/servicers/admin.py
  app/backend/src/tests/test_admin.py
  app/backend/src/tests/test_notifications.py
  app/backend/templates/v2/generated_html/new_blog_post.html
  app/backend/templates/v2/new_blog_post.mjml
  app/backend/templates/v2/new_blog_post.txt
  app/proto/admin.proto
  app/proto/notification_data.proto
  app/web/components/Icons/index.ts
  app/web/features/notifications/EditNotificationSettingsPage.tsx
  app/web/features/notifications/locales/en.json
  app/web/features/notifications/utils/constants.tsx
Labels: release notes: pending

#6068 Only list notifications that are set to be delivered by push in tray
  app/backend/src/couchers/notifications/settings.py
  app/backend/src/couchers/servicers/notifications.py
  app/backend/src/tests/test_notifications.py
Labels: release notes: pending

#6067 Email fixes
  app/backend/requirements.in
  app/backend/requirements.txt
  app/backend/src/couchers/notifications/render.py
  app/backend/src/couchers/templates/v2.py
  app/backend/templates/v2/comment_reply.mjml
  app/backend/templates/v2/discussion_comment.mjml
  app/backend/templates/v2/discussion_create.mjml
  app/backend/templates/v2/event_cancel.mjml
  app/backend/templates/v2/event_comment.mjml
  app/backend/templates/v2/event_create.mjml
  app/backend/templates/v2/event_create.txt
  app/backend/templates/v2/event_invite_organizer.mjml
  app/backend/templates/v2/event_update.mjml
  app/backend/templates/v2/generated_html/comment_reply.html
  app/backend/templates/v2/generated_html/discussion_comment.html
  app/backend/templates/v2/generated_html/discussion_create.html
  app/backend/templates/v2/generated_html/event_cancel.html
  app/backend/templates/v2/generated_html/event_comment.html
  app/backend/templates/v2/generated_html/event_create.html
  app/backend/templates/v2/generated_html/event_invite_organizer.html
  app/backend/templates/v2/generated_html/event_update.html
Labels: release notes: pending

#6065 Remove friend ability
  app/web/components/ConfirmationDialogWrapper.tsx
  app/web/components/EllipsisMenu.tsx
  app/web/features/connections/friends/FriendItem.test.tsx
  app/web/features/connections/friends/FriendItem.tsx
  app/web/features/connections/friends/FriendList.tsx
  app/web/features/connections/friends/FriendSummaryView.tsx
  app/web/features/connections/friends/useFriendList.ts
  app/web/features/connections/locales/en.json
  app/web/features/queryKeys.ts
  app/web/service/api.ts
Labels: release notes: pending

#6026 Reference flow: Did Stay & Private Text
  app/backend/src/tests/test_email.py
  app/backend/templates/system/reference_report.md
  app/web/features/profile/constants.ts
  app/web/features/profile/locales/de.json
  app/web/features/profile/locales/en.json
  app/web/features/profile/locales/zh_Hans.json
  app/web/features/profile/view/ReferenceList.tsx
  app/web/features/profile/view/ReferenceListItem.tsx
  app/web/features/profile/view/References.tsx
  app/web/features/profile/view/leaveReference/LeaveReferencePage.test.tsx
  app/web/features/profile/view/leaveReference/LeaveReferencePage.tsx
  app/web/features/profile/view/leaveReference/ReferenceForm.tsx
  app/web/features/profile/view/leaveReference/formSteps/Appropriate.tsx
  app/web/features/profile/view/leaveReference/formSteps/DidStay.tsx
  app/web/features/profile/view/leaveReference/formSteps/PrivateFeedback.tsx
  app/web/features/profile/view/leaveReference/formSteps/Rating.tsx
  app/web/features/profile/view/leaveReference/formSteps/ReferenceStepHeader.tsx
  app/web/features/profile/view/leaveReference/formSteps/Text.tsx
  app/web/features/profile/view/leaveReference/formSteps/submit/ReferenceOverview.tsx
  app/web/features/profile/view/leaveReference/formSteps/submit/SubmitReference.tsx
  app/web/features/profile/view/leaveReference/formSteps/submit/ThankYouReference.tsx
  app/web/pages/leave-reference/[[...slug]].tsx
  app/web/routes.ts
  app/web/service/references.ts
Labels: release notes: pending
